### ISSUE TITLE
剪裁出来的位置与剪裁框中的位置不对

### ISSUE THREAD

**Issue by yxkrrhx** [xuehuayous/Android-Crop#4]
剪裁出来的图片位置，与在剪裁前的剪裁框中预览出来的位置不同，发生概率极高，每10次有2次

**Comment by yxkrrhx** [comment]
比如长图片将预览框对齐到图片的底部剪裁，剪裁出来的图片并没有对齐图片的底部，发生概率太高了
与cropImage()中这段代码的第一行top计算错误有关，望楼主早日修复
   int top = (int) ((mCropRect.top - currentImageRect.top) / currentScale);
        int left = (int) ((mCropRect.left - currentImageRect.left) / currentScale);
        int width = (int) (mCropRect.width() / currentScale);
        int height = (int) (mCropRect.height() / currentScale);

**Comment by WenkaiZhou** [comment]
这个当时在[Yalantis/uCrop](https://github.com/Yalantis/uCrop)修改的，目前[Yalantis/uCrop](https://github.com/Yalantis/uCrop)又进行了一系列的优化，推荐你使用uCrop这个去做，我们项目里也是使用的uCrop。另外你可以参考下这个项目的使用[Android-ImageCrop](https://github.com/xuehuayous/Android-ImageCrop)

**Comment by yxkrrhx** [comment]
嗯，原生的uCrop的确使用灵活，且已经优化了好多代码，自定义起来也很简单。感谢楼主告知。
